# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('lastName', models.CharField(db_column='LastName', max_length=255)),
                ('email', models.EmailField(db_column='Email', max_length=255)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('events', models.ManyToManyField(blank=True, to='events.Event')),
            ],
        ),
    ]
