# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('type', models.CharField(choices=[('CO', 'Concert'), ('SP', 'Sport'), ('CI', 'Cinema'), ('TH', 'Theater'), ('PR', 'Programming'), ('OT', 'Other')], db_column='Type', default='OT', max_length=2)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('startDateTime', models.DateTimeField(db_column='StartDateTime')),
                ('finishDateTime', models.DateTimeField(db_column='FinishDateTime')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.City')),
            ],
        ),
    ]
