# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='placeId',
            field=models.CharField(db_column='PlaceId', default='ChIJKcumLf2bP44RFDmjIFVjnSM', editable=False, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
