# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20170105_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.ForeignKey(db_column='CityId', on_delete=django.db.models.deletion.CASCADE, to='events.City'),
        ),
    ]
