# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20170105_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(db_column='Latitude', decimal_places=5, default=4.71098, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(db_column='Longitude', decimal_places=5, default=-74.07209, max_digits=8),
            preserve_default=False,
        ),
    ]
