# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170105_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='placeId',
            field=models.CharField(db_column='PlaceId', max_length=255, unique=True),
        ),
    ]
