# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20170105_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(db_column='Latitude', decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(db_column='Longitude', decimal_places=6, max_digits=9),
        ),
    ]
